apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/apigateway.services.k8s.aws_apiintegrationresponses.yaml
  - bases/apigateway.services.k8s.aws_apikeys.yaml
  - bases/apigateway.services.k8s.aws_apimethodresponses.yaml
  - bases/apigateway.services.k8s.aws_authorizers.yaml
  - bases/apigateway.services.k8s.aws_deployments.yaml
  - bases/apigateway.services.k8s.aws_integrations.yaml
  - bases/apigateway.services.k8s.aws_methods.yaml
  - bases/apigateway.services.k8s.aws_resources.yaml
  - bases/apigateway.services.k8s.aws_restapis.yaml
  - bases/apigateway.services.k8s.aws_stages.yaml
  - bases/apigateway.services.k8s.aws_vpclinks.yaml
