apiVersion: v1
name: apigateway-chart
description: A Helm chart for the ACK service controller for Amazon API Gateway (apigateway)
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/aws-controllers-k8s/apigateway-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/apigateway-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: apigateway Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/apigateway-maintainer
keywords:
  - aws
  - kubernetes
  - apigateway
